CREATE SCHEMA IF NOT EXISTS ebike_auth;
CREATE SCHEMA IF NOT EXISTS ebike_product;
CREATE SCHEMA IF NOT EXISTS ebike_order;
CREATE SCHEMA IF NOT EXISTS ebike_chatbot;
CREATE SCHEMA IF NOT EXISTS ebike_user;
