spring.application.name=ebike-backend
spring.profiles.default=dev

server.port=8080
server.servlet.context-path=/api/v1

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
